name: CI Grader

on: push

jobs:
  test:

    runs-on: ubuntu-latest
    container:
      image: ufscar/cigrader:ubuntu-24_04
      options: --privileged
    env:
      PROF_GITHUB: ${{ secrets.PROF_GITHUB }}

    steps:
      - uses: actions/checkout@v2
      - uses: jitterbit/get-changed-files@v1
        id: files
        with:
          format: 'json'
      - uses: actions/github-script@0.3.0
        id: author-date
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const commit_details = await github.git.getCommit({owner: context.repo.owner, repo: context.repo.repo, commit_sha: context.sha});
            return commit_details.data.author.date
      - name: Grader
        #uses: coactions/setup-xvfb@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          COMMIT_TIME: ${{ steps.author-date.outputs.result }}
          COMMIT_FILES: ${{ steps.files.outputs.all }}
#        with:
        run: python3 .github/workflows/grade.py
